#ifndef AUCTIONCOMMON_SERVICEERROR_H_
#define AUCTIONCOMMON_SERVICEERROR_H_

namespace nsl {

enum COMMON_ERROR_LIST
{
    ERROR_NOT_USE = -1,
    ERROR_NONE_ = 0,
    ERROR_UNKNOWN_FAIL_ = 1,
    ERROR_DB_CONNECTION_LOST = 2,
    ERROR_STOP_CALLED_ = 3,
    AUCTION_ERROR_START = 4,
    ERROR_NONE_BOT_COLLECTED = 5,
    SSO_ERROR_START = 1000,
    ERROR_COMMON_LIST_MAX = 1000
};

enum AUCTION_ERROR_LIST
{
    ERROR_AUCTION_FAIL_ID_CREATE_ = 4,
    ERROR_AUCTION_CONNECTION_LOST_ = 5,
    ERROR_AUCTION_CONNECT_GA_FAIL_ = 6,
    ERROR_AUCTION_REGIST_GA_FAIL_ID_DUPLICATE_ = 7,
    ERROR_AUCTION_STOP_CALLED_ = 8,
    ERROR_AUCTION_FAIL_MEMORY_ALLOC_ = 9,
    ERROR_AUCTION_FAIL_REGIST_ITEM_ = 10,
    ERROR_AUCTION_FAIL_UNREGIST_ITEM_ = 11,
    ERROR_AUCTION_FAIL_INSERT_CHARACTER_ = 12,
    ERROR_AUCTION_FAIL_INSERT_AVERAGE_PRICE_ = 13,
    ERROR_AUCTION_FAIL_INSERT_BY_ITEM_ID = 14,
    ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_RARITY_UPGRADE_LV = 15,
    ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_RARITY_UPGRADE = 16,
    ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_UPGRADE_LV = 17,
    ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_UPGRADE = 18,
    ERROR_CANNOT_FIND_AUCTION_DATA_TO_DELETE_FROM_SEARCH_MODULE = 19,
    ERROR_AUCTION_FAIL_SEARCH_BY_ITEM_ID = 20,
    ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_RARITY_UPGRADE_LV = 21,
    ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_RARITY_UPGRADE = 22,
    ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_UPGRADE_LV = 23,
    ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_UPGRADE = 24,
    ERROR_INVALID_CATEGORY_ID = 25,
    ERROR_INVALID_RARITY = 26,
    ERROR_INVALID_LV = 27,
    ERROR_INVALID_UPGRADE = 28,
    ERROR_INVALID_ITEM_COUNT = 29,
    ERROR_AUCTION_EXCEED_REGISTED_ITEM_NUM_ = 30,
    ERROR_AUCTION_EXCEED_INSTANT_PRICE_ = 31,
    ERROR_AUCTION_WRONG_ITEM_UPGRADE_VALUE_ = 32,
    ERROR_AUCTION_WRONG_AVERAGE_PRICE_ = 33,
    ERROR_AUCTION_INVALID_CHARACTER_ID_ = 34,
    ERROR_AUCTION_INVALID_ITEM_ID_ = 35,
    ERROR_AUCTION_INVALID_AUCTION_ID_ = 36,
    ERROR_AUCTION_INVALID_BIDDING_PRICE_ = 37,
    ERROR_AUCTION_INVALID_PRICE_ = 38,
    ERROR_AUCTION_INVALID_ITEM_INFO_ = 39,
    ERROR_AUCTION_INVALID_EXPIRED_ITEM_ = 40,
    ERROR_AUCTION_INVALID_ARGUMENT_ = 41,
    ERROR_AUCTION_REGISTER_UNAUTHORIZE_ = 42,
    ERROR_AUCTION_UNREGISTER_UNAUTHORIZE_ = 43,
    ERROR_AUCTION_NOT_EXIST_REGISTED_ITEM_ = 44,
    ERROR_AUCTION_BIDDING_MY_ITEM = 45,
    ERROR_AUCTION_BIDDING_ALREADY = 46,
    ERROR_AUCTION_BIDDING_MONEY_SHORTAGE = 47,
    ERROR_AUCTION_NO_PRIVATE_STORE_OPEN_ = 48,
    ERROR_AUCTION_BUSY = 49,
    ERROR_AUCTION_INVALID_AUCTION_TYPE = 50,
    ERROR_INVALID_REFINE = 51,
    ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_REFINE = 52,
    ERROR_AUCTION_NOT_READY = 53,
    ERROR_AUCTION_REGIST_GP_FAIL_ID_DUPLICATE_ = 54,
    ERROR_AUCTION_REGIST_GP_FAIL_LOW_PRICE_ = 55,
    ERROR_AUCTION_END_ = 56
};

} // namespace nsl

#endif // AUCTIONCOMMON_SERVICEERROR_H_
