// Reconstructed from zergsvr binary：
// ZERGLING_STAT_ITEM_WITH_NAME 为头文件内 static 数组（每个包含 TU 各持一份，
// .bss 动态构造，与二进制每 TU 一个 STB_LOCAL 25 x 92 字节数组一致）。
#ifndef SECSVR_SRC_COMMSVR_ZERGSVR_ZERG_STAT_DEFINE_H_H_
#define SECSVR_SRC_COMMSVR_ZERGSVR_ZERG_STAT_DEFINE_H_H_

#include "output/commlib/zenlib/release/include/zen_server_status.h"

// line 44：statics_id 0x2329..0x2341，名称与类型（STATICS_PER_FIVE_MINTUES /
// STATICS_ABSOLUTE_VALUE）与二进制静态初始化逐项一致。
static ZEN_STATUS_ITEM_WITHNAME ZERGLING_STAT_ITEM_WITH_NAME[] = {
    ZEN_STATUS_ITEM_WITHNAME(0x2329, STATICS_PER_FIVE_MINTUES, "ZERG_ACCEPT_PEER_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232a, STATICS_ABSOLUTE_VALUE, "ZERG_ACCEPT_PEER_NUMBER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232b, STATICS_PER_FIVE_MINTUES, "ZERG_CONNECT_PEER_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232c, STATICS_ABSOLUTE_VALUE, "ZERG_CONNECT_PEER_NUMBER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232d, STATICS_ABSOLUTE_VALUE, "ZERG_BUFFER_STORAGE_NUMBER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232e, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_FRAME_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x232f, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_FRAME_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2330, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_BYTES_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2331, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_BYTES_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2332, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_SUCC_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2333, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_SUCC_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2334, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_FAIL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2335, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_FAIL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2336, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_BLOCK_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2337, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_BLOCK_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2338, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_RECV_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2339, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_SEND_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233a, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_RECV_FAIL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233b, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_SEND_FAIL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233c, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_RECV_BYTES_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233d, STATICS_PER_FIVE_MINTUES, "ZERG_UDP_SEND_BYTES_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233e, STATICS_PER_FIVE_MINTUES, "ZERG_RECV_PIPE_FULL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x233f, STATICS_ABSOLUTE_VALUE, "ZERG_RECV_PIPE_FULL_NUMBER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2340, STATICS_PER_FIVE_MINTUES, "ZERG_SEND_LIST_FULL_COUNTER"),
    ZEN_STATUS_ITEM_WITHNAME(0x2341, STATICS_ABSOLUTE_VALUE, "ZERG_SEND_LIST_FULL_NUMBER"),
};

#endif // SECSVR_SRC_COMMSVR_ZERGSVR_ZERG_STAT_DEFINE_H_H_
