# -*- coding: utf-8 -*-
"""MySQL 客户端 / mysys / strings / charset / vio 库符号精确豁免表。

ORIG 静态链接真实 libmysqlclient（含 mysys、strings、charset、dtoa 等），
重建侧在 source/Library3rd/MySQL 提供同一库，但编译器/版本/归档不同导致
大量 C 符号（my_*、vio_*、net_*、cli_*、alloc_* 等）无法逐字 identical。
按 docs/identical_brief_for_agents.md §2 用户规则（MySQL/zlib/NCrypto 等
第三方基础库豁免），这些符号移出 IDENTICAL/NEAR/DIFF/MISSING 统计。

这里使用「精确符号名集合」而非宽泛前缀，避免误伤项目符号
（如 CMySql::set_compress_option、yaSSL::*::get_type 等）。
列表由 manager/dbmw manifest 中所有非 _Z* 的非 identical 符号生成。
"""

MYSQL_EXEMPT_SYMBOLS = frozenset((
    '_my_thread_var', 'add_collation', 'add_compiled_collation', 'add_directory', 'add_init_command', 'alloc_dynamic',
    'alloc_root', 'alloc_stmt_fields', 'allocate_dynamic', 'array_append_string_unique', 'atoi_octal', 'bchange',
    'build_tree', 'check_date', 'check_scramble', 'check_scramble_323', 'cleanup_dirname', 'cli_advanced_command',
    'cli_flush_use_result', 'cli_list_fields', 'cli_read_binary_rows', 'cli_read_change_user_result', 'cli_read_prepare_result', 'cli_read_query_result',
    'cli_read_rows', 'cli_read_statistics', 'cli_safe_read', 'cli_stmt_execute', 'cli_unbuffered_fetch', 'cli_use_result',
    'comp_names', 'compress', 'compress_block', 'convert_dirname', 'copy_typelib', 'create_fromuni',
    'create_random_string', 'create_tailoring', 'cs_alloc', 'cs_enter', 'cs_leave', 'cs_value',
    'd2b', 'default_local_infile_end', 'default_local_infile_error', 'default_local_infile_init', 'default_local_infile_read', 'delete_dynamic',
    'delete_dynamic_element', 'directory_file_name', 'dirname_length', 'dirname_part', 'dtoa.clone.0', 'end_server',
    'fetch_datetime_with_conversion', 'fetch_float_with_conversion', 'fetch_long_with_conversion', 'fetch_result_bin', 'fetch_result_date', 'fetch_result_datetime',
    'fetch_result_int64', 'fetch_result_str', 'fetch_result_time', 'fetch_result_with_conversion', 'fetch_string_with_conversion', 'fill_uchar',
    'find_type', 'find_type_or_exit', 'find_typeset', 'finish_client_errs', 'flush_one_result', 'fn_ext',
    'fn_format', 'free_charsets', 'free_defaults', 'free_old_query', 'free_root', 'free_rows',
    'free_vio_ssl_acceptor_fd', 'freeze_size', 'get_argument', 'get_charset', 'get_charset_by_csname', 'get_charset_by_name',
    'get_charset_name', 'get_charset_number', 'get_charsets_dir', 'get_collation_number', 'get_defaults_options', 'get_dynamic',
    'get_internal_charset', 'get_salt_from_password', 'get_salt_from_password_323', 'get_type', 'handle_default_option', 'handle_local_infile',
    'has_path', 'hash_password', 'init_alloc_root', 'init_available_charsets.clone.0', 'init_client_errs', 'init_compiled_charsets',
    'init_default_directories', 'init_dynamic_array', 'init_dynamic_array2', 'init_state_maps', 'insert_dynamic', 'int2str',
    'intern_filename', 'ismbchar_euc_kr', 'lex2str', 'list_cons', 'list_free', 'list_walk',
    'll2str', 'load_defaults', 'longlong10_to_str', 'lshift', 'make_password_from_salt', 'make_password_from_salt_323',
    'make_scrambled_password', 'make_scrambled_password_323', 'make_type', 'memdup_root', 'multadd', 'multi_alloc_root',
    'my_TIME_to_str', 'my_atof', 'my_casedn_str_utf8mb3', 'my_casedn_str_utf8mb4', 'my_casedn_ucs2', 'my_casedn_utf16',
    'my_casedn_utf8mb3', 'my_casedn_utf8mb4', 'my_caseup_str_utf8mb3', 'my_caseup_str_utf8mb4', 'my_caseup_ucs2', 'my_caseup_utf16',
    'my_caseup_utf32', 'my_caseup_utf8mb3', 'my_caseup_utf8mb4', 'my_charset_same', 'my_close', 'my_coll_init_simple',
    'my_coll_lexem_print_error', 'my_connect', 'my_date_to_str', 'my_datetime_to_str', 'my_dir', 'my_dirend',
    'my_end', 'my_error', 'my_error_register', 'my_error_unregister', 'my_error_unregister_all', 'my_fclose',
    'my_fcvt', 'my_fdopen', 'my_filename', 'my_fileno', 'my_fill_8bit', 'my_fopen',
    'my_fread', 'my_fseek', 'my_fstat', 'my_ftell', 'my_fwrite', 'my_gcvt',
    'my_getsystime', 'my_getwd', 'my_hash_sort_any_uca', 'my_hash_sort_latin1_de', 'my_hash_sort_simple', 'my_hash_sort_ucs2',
    'my_hash_sort_ucs2_bin', 'my_hash_sort_ucs2_uca', 'my_hash_sort_utf16', 'my_hash_sort_utf16_bin', 'my_hash_sort_utf8mb3', 'my_hash_sort_utf8mb4',
    'my_init', 'my_init_time', 'my_instr_mb', 'my_instr_simple', 'my_is_symlink', 'my_ismbchar_utf8mb3',
    'my_l10tostr_mb2_or_mb4', 'my_like_range_big5', 'my_like_range_cp932', 'my_like_range_czech', 'my_like_range_gbk', 'my_like_range_mb',
    'my_like_range_simple', 'my_like_range_sjis', 'my_like_range_ucs2', 'my_like_range_utf16', 'my_like_range_utf32', 'my_like_range_win1250ch',
    'my_ll10tostr_mb2_or_mb4', 'my_load_defaults', 'my_load_path', 'my_long10_to_str_8bit', 'my_longlong10_to_str_8bit', 'my_malloc',
    'my_mb_ctype_mb', 'my_mb_wc_big5', 'my_mb_wc_cp932', 'my_mb_wc_euc_jp', 'my_mb_wc_euc_kr', 'my_mb_wc_filename',
    'my_mb_wc_gb2312', 'my_mb_wc_gbk', 'my_mb_wc_latin1', 'my_mb_wc_sjis', 'my_mb_wc_tis620', 'my_memdup',
    'my_message', 'my_message_no_curses', 'my_micro_time', 'my_micro_time_and_time', 'my_multi_malloc', 'my_net_init',
    'my_net_local_init', 'my_net_read', 'my_net_write', 'my_no_flags_free', 'my_numcells_cp932', 'my_numcells_mb',
    'my_numcells_sjis', 'my_numchars_utf16', 'my_once_alloc', 'my_once_free', 'my_once_memdup', 'my_once_strdup',
    'my_open', 'my_parse_charset_xml', 'my_pipe_sig_handler', 'my_print_default_files', 'my_printf_error', 'my_printv_error',
    'my_qsort', 'my_read', 'my_read_charset_file', 'my_readlink', 'my_real_read', 'my_realloc',
    'my_realpath', 'my_register_filename', 'my_rnd_init', 'my_scan_utf32', 'my_search_option_files', 'my_setwd',
    'my_snprintf', 'my_snprintf_8bit', 'my_snprintf_mb2', 'my_snprintf_utf32', 'my_stat', 'my_str_free_default',
    'my_str_malloc_default', 'my_strcasecmp_8bit', 'my_strcasecmp_bin', 'my_strcasecmp_mb_bin', 'my_strcasecmp_utf8mb3', 'my_strcasecmp_utf8mb4',
    'my_strdup', 'my_strndup', 'my_strnncoll_any_uca', 'my_strnncoll_big5', 'my_strnncoll_cp932', 'my_strnncoll_czech',
    'my_strnncoll_gbk', 'my_strnncoll_gbk_internal', 'my_strnncoll_latin1_de', 'my_strnncoll_sjis', 'my_strnncoll_tis620', 'my_strnncoll_ucs2',
    'my_strnncoll_ucs2_bin', 'my_strnncoll_ucs2_uca', 'my_strnncoll_utf16', 'my_strnncoll_utf16_bin', 'my_strnncoll_utf32', 'my_strnncoll_utf32_bin',
    'my_strnncoll_utf8mb3', 'my_strnncoll_utf8mb4', 'my_strnncoll_win1250ch', 'my_strnncollsp_8bit_bin', 'my_strnncollsp_any_uca', 'my_strnncollsp_big5',
    'my_strnncollsp_binary', 'my_strnncollsp_cp932', 'my_strnncollsp_czech', 'my_strnncollsp_gbk', 'my_strnncollsp_latin1_de', 'my_strnncollsp_mb_bin',
    'my_strnncollsp_simple', 'my_strnncollsp_sjis', 'my_strnncollsp_tis620', 'my_strnncollsp_ucs2', 'my_strnncollsp_ucs2_bin', 'my_strnncollsp_ucs2_uca',
    'my_strnncollsp_utf16', 'my_strnncollsp_utf16_bin', 'my_strnncollsp_utf32', 'my_strnncollsp_utf8mb3', 'my_strnncollsp_utf8mb4', 'my_strnncollsp_win1250ch',
    'my_strntod_8bit', 'my_strntod_mb2_or_mb4', 'my_strntol_8bit', 'my_strntoll_8bit', 'my_strntoll_mb2_or_mb4', 'my_strntoul_8bit',
    'my_strntoul_mb2_or_mb4', 'my_strntoull10rnd_8bit', 'my_strntoull10rnd_mb2_or_mb4', 'my_strntoull_8bit', 'my_strntoull_mb2_or_mb4', 'my_strnxfrm_8bit_bin',
    'my_strnxfrm_any_uca', 'my_strnxfrm_big5', 'my_strnxfrm_czech', 'my_strnxfrm_gbk', 'my_strnxfrm_latin1_de', 'my_strnxfrm_mb',
    'my_strnxfrm_simple', 'my_strnxfrm_tis620', 'my_strnxfrm_uca', 'my_strnxfrm_ucs2_uca', 'my_strnxfrm_unicode', 'my_strnxfrm_win1250ch',
    'my_strtod', 'my_strtoll10', 'my_strtoll10_8bit', 'my_strtoll10_mb2', 'my_strtoll10_utf32', 'my_strxfrm_desc_and_reverse',
    'my_strxfrm_flag_normalize', 'my_strxfrm_pad_desc_and_reverse', 'my_strxfrm_pad_desc_and_reverse_utf32', 'my_symlink', 'my_sync', 'my_system_gmt_sec',
    'my_thread_dbug_id', 'my_thread_destroy_mutex', 'my_thread_end', 'my_thread_global_end', 'my_thread_global_init', 'my_thread_init',
    'my_thread_name', 'my_thread_var_mutex_in_use', 'my_time', 'my_time_possible_from_micro', 'my_time_to_str', 'my_uca_scanner_init_any',
    'my_uca_scanner_init_ucs2', 'my_uca_scanner_next_any', 'my_uca_scanner_next_ucs2', 'my_uni_utf16', 'my_vsnprintf', 'my_wait_for_other_threads_to_die',
    'my_wc_mb_big5', 'my_wc_mb_cp932', 'my_wc_mb_euc_jp', 'my_wc_mb_euc_kr', 'my_wc_mb_filename', 'my_wc_mb_gb2312',
    'my_wc_mb_gbk', 'my_wc_mb_latin1', 'my_wc_mb_sjis', 'my_wc_mb_tis620', 'my_wc_mb_utf8mb3', 'my_wc_mb_utf8mb4',
    'my_well_formed_len_cp932', 'my_well_formed_len_gbk', 'my_well_formed_len_sjis', 'my_wildcmp_8bit', 'my_wildcmp_bin', 'my_wildcmp_mb',
    'my_wildcmp_mb_bin', 'my_wildcmp_uca', 'my_wildcmp_ucs2_bin', 'my_wildcmp_ucs2_ci', 'my_wildcmp_unicode', 'my_wildcmp_utf16_bin',
    'my_wildcmp_utf16_ci', 'my_wildcmp_utf32_bin', 'my_wildcmp_utf32_ci', 'my_wildcmp_utf8mb3', 'my_wildcmp_utf8mb4', 'my_xml_error_lineno',
    'my_xml_leave', 'my_xml_parse', 'my_xml_scan', 'myodbc_remove_escape', 'net_clear', 'net_clear_error',
    'net_end', 'net_field_length', 'net_flush', 'net_real_write', 'net_realloc', 'net_write_buff',
    'net_write_command', 'new_VioSSLAcceptorFd', 'new_VioSSLConnectorFd', 'new_VioSSLFd', 'normalize_dirname', 'number_to_datetime',
    'octet2hex', 'opt_flush_ok_packet', 'pack_dirname', 'packfrm', 'pow5mult', 'print_defaults',
    'read_user_name', 'report_errors', 'reset_root_defaults', 'reset_stmt_handle', 'resolve_charset', 'resolve_collation',
    'scramble', 'scramble_323', 'search_default_file_with_ext', 'send_tree', 'set_dynamic', 'set_stmt_errmsg',
    'set_stmt_error', 'setup_one_fetch_function', 'skip_result_string', 'skip_result_with_length', 'ssl_do', 'sslaccept',
    'sslconnect', 'stmt_read_row_from_cursor', 'stmt_read_row_no_result_set', 'stmt_read_row_unbuffered', 'store_param_date', 'store_param_datetime',
    'store_param_str', 'store_param_time', 'str2int', 'str_to_datetime', 'str_to_time', 'strdup_root',
    'strmake_root', 'system_filename', 'test_if_hard_path', 'unpack_dirname', 'unpack_fields', 'unpack_filename',
    'unpackfrm', 'updatewindow', 'vio_blocking', 'vio_close', 'vio_delete', 'vio_end',
    'vio_errno', 'vio_fastsend', 'vio_keepalive', 'vio_new', 'vio_peek_read', 'vio_peer_addr',
    'vio_pending', 'vio_poll_read', 'vio_read', 'vio_read_buff', 'vio_reset', 'vio_should_retry',
    'vio_ssl_close', 'vio_ssl_delete', 'vio_ssl_read', 'vio_ssl_write', 'vio_timeout', 'vio_verify_callback',
    'vio_was_interrupted', 'vio_write', 'wait_for_free_space', 'zError',
))
