// nsl::ServiceError.cpp
#include <stdio.h>
#include <map>
#include <string>

#include "ServiceError.h"
#include "TraceLog.h"

#define REGISTER_SERVICE_ERROR(enum_type, err) \
    sprintf(nsl::___errstr_tmp___, "[%d:%s]", err, #err); \
    nsl::___errstr_map___.insert(std::make_pair<enum_type, char(&)[2048]>(err, nsl::___errstr_tmp___))

namespace nsl {

std::map<int, std::string> ___errstr_map___;
char ___errstr_tmp___[2048];

void InitServiceErrorStr()
{
    sprintf(___errstr_tmp___, "[%d:%s]", ERROR_NOT_USE, "***GetErrorStr() failed***");
    ___errstr_map___.insert(std::make_pair<COMMON_ERROR_LIST, char(&)[2048]>(COMMON_ERROR_LIST(ERROR_NOT_USE), ___errstr_tmp___));
    sprintf(___errstr_tmp___, "[%d:%s]", ERROR_NONE_, "ERROR_NONE_");
    ___errstr_map___.insert(std::make_pair<COMMON_ERROR_LIST, char(&)[2048]>(COMMON_ERROR_LIST(ERROR_NONE_), ___errstr_tmp___));
    sprintf(___errstr_tmp___, "[%d:%s]", ERROR_UNKNOWN_FAIL_, "ERROR_UNKNOWN_FAIL_");
    ___errstr_map___.insert(std::make_pair<COMMON_ERROR_LIST, char(&)[2048]>(COMMON_ERROR_LIST(ERROR_UNKNOWN_FAIL_), ___errstr_tmp___));
    sprintf(___errstr_tmp___, "[%d:%s]", ERROR_DB_CONNECTION_LOST, "ERROR_DB_CONNECTION_LOST");
    ___errstr_map___.insert(std::make_pair<COMMON_ERROR_LIST, char(&)[2048]>(COMMON_ERROR_LIST(ERROR_DB_CONNECTION_LOST), ___errstr_tmp___));
    sprintf(___errstr_tmp___, "[%d:%s]", ERROR_STOP_CALLED_, "ERROR_STOP_CALLED_");
    ___errstr_map___.insert(std::make_pair<COMMON_ERROR_LIST, char(&)[2048]>(COMMON_ERROR_LIST(ERROR_STOP_CALLED_), ___errstr_tmp___));
}

const char* GetErrorStr(int err)
{
    std::map<int, std::string>::iterator it = ___errstr_map___.find(err);
    if (it == ___errstr_map___.end())
    {
        G_TraceLog()->sysLog(7, "GetErrorStr() failed. error_no : %d\n", err);
        return ___errstr_map___.find(ERROR_NOT_USE)->second.c_str();
    }
    return it->second.c_str();
}

} // namespace nsl

using namespace nsl;

void SetAuctionServiceErrorStr()
{
    nsl::InitServiceErrorStr();
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_ID_CREATE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_CONNECTION_LOST_);
    REGISTER_SERVICE_ERROR(COMMON_ERROR_LIST, ERROR_STOP_CALLED_);
    REGISTER_SERVICE_ERROR(COMMON_ERROR_LIST, ERROR_DB_CONNECTION_LOST);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_CONNECT_GA_FAIL_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_REGIST_GA_FAIL_ID_DUPLICATE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_STOP_CALLED_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_MEMORY_ALLOC_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_REGIST_ITEM_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_UNREGIST_ITEM_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_CHARACTER_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_AVERAGE_PRICE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_BY_ITEM_ID);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_RARITY_UPGRADE_LV);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_RARITY_UPGRADE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_UPGRADE_LV);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_INSERT_BY_CATEGORY_UPGRADE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_CANNOT_FIND_AUCTION_DATA_TO_DELETE_FROM_SEARCH_MODULE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_SEARCH_BY_ITEM_ID);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_RARITY_UPGRADE_LV);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_RARITY_UPGRADE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_UPGRADE_LV);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_FAIL_SEARCH_BY_CATEGORY_UPGRADE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_INVALID_CATEGORY_ID);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_INVALID_RARITY);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_INVALID_LV);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_INVALID_UPGRADE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_INVALID_ITEM_COUNT);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_EXCEED_REGISTED_ITEM_NUM_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_EXCEED_INSTANT_PRICE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_WRONG_ITEM_UPGRADE_VALUE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_WRONG_AVERAGE_PRICE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_CHARACTER_ID_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_ITEM_ID_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_AUCTION_ID_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_BIDDING_PRICE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_PRICE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_ITEM_INFO_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_EXPIRED_ITEM_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_ARGUMENT_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_REGISTER_UNAUTHORIZE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_UNREGISTER_UNAUTHORIZE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_NOT_EXIST_REGISTED_ITEM_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_BIDDING_MY_ITEM);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_BIDDING_ALREADY);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_BIDDING_MONEY_SHORTAGE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_NO_PRIVATE_STORE_OPEN_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_BUSY);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_INVALID_AUCTION_TYPE);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_NOT_READY);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_REGIST_GP_FAIL_ID_DUPLICATE_);
    REGISTER_SERVICE_ERROR(AUCTION_ERROR_LIST, ERROR_AUCTION_END_);
}
