// Auto-generated empty header stub from DWARF line info
// Original path: output/commlib/zenlib/release/include/zen_thread_msgque_sema.h
#ifndef SECSVR_OUTPUT_COMMLIB_ZENLIB_RELEASE_INCLUDE_ZEN_THREAD_MSGQUE_SEMA_H_H_
#define SECSVR_OUTPUT_COMMLIB_ZENLIB_RELEASE_INCLUDE_ZEN_THREAD_MSGQUE_SEMA_H_H_

#endif // SECSVR_OUTPUT_COMMLIB_ZENLIB_RELEASE_INCLUDE_ZEN_THREAD_MSGQUE_SEMA_H_H_
