#ifndef DNF_GAME_GAMEENUMS_H_
#define DNF_GAME_GAMEENUMS_H_

// df_game_r Game/ 全局枚举定义（从 GameStubs.cpp 拆出，拓扑最底层）。
// 枚举无依赖，所有 TU 均可安全 include。

#ifndef DNF_ENUM_INVEN_TYPE_DEFINED
#define DNF_ENUM_INVEN_TYPE_DEFINED
enum INVEN_TYPE
{
    INVEN_TYPE_INVEN = 0,
    INVEN_TYPE_EQUIP = 1,
    INVEN_TYPE_AVATAR = 2,
    INVEN_TYPE_CREATURE = 3,
    INVEN_TYPE_5 = 5,
    INVEN_TYPE_6 = 6
};
#endif

#ifndef DNF_ENUM_EITEMADDREASON_DEFINED
#define DNF_ENUM_EITEMADDREASON_DEFINED
enum eItemAddReason { eItemAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EMONEYADDREASON_DEFINED
#define DNF_ENUM_EMONEYADDREASON_DEFINED
enum eMoneyAddReason
{
    eMoneyAddReason_0 = 0,
    eMoneyAddReason_4 = 4,
    eMoneyAddReason_7 = 7,
    eMoneyAddReason_0x1a = 0x1a
};
#endif
#ifndef DNF_ENUM_EITEMDELREASON_DEFINED
#define DNF_ENUM_EITEMDELREASON_DEFINED
enum eItemDelReason
{
    eItemDelReason_0 = 0,
    eItemDelReason_3 = 3
};
#endif
#ifndef DNF_ENUM_EMONEYSUBREASON_DEFINED
#define DNF_ENUM_EMONEYSUBREASON_DEFINED
enum eMoneySubReason { eMoneySubReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ECOINSUBREASON_DEFINED
#define DNF_ENUM_ECOINSUBREASON_DEFINED
enum eCoinSubReason { eCoinSubReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EAVATARITEMADDREASON_DEFINED
#define DNF_ENUM_EAVATARITEMADDREASON_DEFINED
enum eAvatarItemAddReason { eAvatarItemAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ITEMSPACE_DEFINED
#define DNF_ENUM_ITEMSPACE_DEFINED
enum ENUM_ITEMSPACE { ENUM_ITEMSPACE_0 = 0 };
#endif
#ifndef DNF_ENUM_CHARAC_EXPAND_TYPE_DEFINED
#define DNF_ENUM_CHARAC_EXPAND_TYPE_DEFINED
enum ENUM_CHARAC_EXPAND_TYPE
{
    ENUM_CHARAC_EXPAND_TYPE_0 = 0,
    ENUM_CHARAC_EXPAND_TYPE_1 = 1,
    ENUM_CHARAC_EXPAND_TYPE_2 = 2,
    ENUM_CHARAC_EXPAND_TYPE_3 = 3,
    ENUM_CHARAC_EXPAND_TYPE_4 = 4,
    ENUM_CHARAC_EXPAND_TYPE_5 = 5,
    ENUM_CHARAC_EXPAND_TYPE_6 = 6,
    ENUM_CHARAC_EXPAND_TYPE_7 = 7,
    ENUM_CHARAC_EXPAND_TYPE_8 = 8,
    ENUM_CHARAC_EXPAND_TYPE_9 = 9,
    ENUM_CHARAC_EXPAND_TYPE_10 = 10,
    ENUM_CHARAC_EXPAND_TYPE_11 = 11,
    ENUM_CHARAC_EXPAND_TYPE_12 = 12,
    ENUM_CHARAC_EXPAND_TYPE_13 = 13,
    ENUM_CHARAC_EXPAND_TYPE_14 = 14,
    ENUM_CHARAC_EXPAND_TYPE_15 = 15,
    ENUM_CHARAC_EXPAND_TYPE_16 = 16,
    ENUM_CHARAC_EXPAND_TYPE_17 = 17,
    ENUM_CHARAC_EXPAND_TYPE_18 = 18,
    ENUM_CHARAC_EXPAND_TYPE_19 = 19
};
#endif
#ifndef DNF_ENUM_DAILYSCHEDULETYPE_DEFINED
#define DNF_ENUM_DAILYSCHEDULETYPE_DEFINED
enum _DailyScheduleType { _DailyScheduleType_0 = 0 };
#endif
#ifndef DNF_ENUM_EQUIPSLOT_DEFINED
#define DNF_ENUM_EQUIPSLOT_DEFINED
enum ENUM_EQUIPSLOT { ENUM_EQUIPSLOT_0 = 0 };
#endif

#ifndef DNF_ENUM_DBLOG_ITEM_TYPE_DEFINED
#define DNF_ENUM_DBLOG_ITEM_TYPE_DEFINED
enum ENUM_DBLOG_ITEM_TYPE { ENUM_DBLOG_ITEM_TYPE_0 = 0 };
#endif
#ifndef DNF_ENUM_SECURITY_PROTCTION_DEFINED
#define DNF_ENUM_SECURITY_PROTCTION_DEFINED
enum SECURITY_PROTCTION
{
    SECURITY_PROTCTION_0 = 0,
    SECURITY_PROTCTION_0x16 = 0x16
};
#endif
#ifndef DNF_ENUM_USERINFO_DEFINED
#define DNF_ENUM_USERINFO_DEFINED
enum ENUM_USERINFO { ENUM_USERINFO_0 = 0 };
#endif

#ifndef DNF_ENUM_ESKILLINITREASON_DEFINED
#define DNF_ENUM_ESKILLINITREASON_DEFINED
enum eSkillInitReason { eSkillInitReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ESKILLADDREASON_DEFINED
#define DNF_ENUM_ESKILLADDREASON_DEFINED
enum eSkillAddReason { eSkillAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ESKILLDELREASON_DEFINED
#define DNF_ENUM_ESKILLDELREASON_DEFINED
enum eSkillDelReason { eSkillDelReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ESPADDREASON_DEFINED
#define DNF_ENUM_ESPADDREASON_DEFINED
enum eSPAddReason { eSPAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ESPSUBREASON_DEFINED
#define DNF_ENUM_ESPSUBREASON_DEFINED
enum eSPSubReason { eSPSubReason_0 = 0 };
#endif
#ifndef DNF_ENUM_ECHANGEGROWTYPEREASON_DEFINED
#define DNF_ENUM_ECHANGEGROWTYPEREASON_DEFINED
enum eChangeGrowTypeReason { eChangeGrowTypeReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EFPADDREASON_DEFINED
#define DNF_ENUM_EFPADDREASON_DEFINED
enum eFPAddReason { eFPAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EFPSUBREASON_DEFINED
#define DNF_ENUM_EFPSUBREASON_DEFINED
enum eFPSubReason { eFPSubReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EWPSUBREASON_DEFINED
#define DNF_ENUM_EWPSUBREASON_DEFINED
enum eWPSubReason { eWPSubReason_0 = 0 };
#endif

#ifndef DNF_ENUM_ETRADEENDREASON_DEFINED
#define DNF_ENUM_ETRADEENDREASON_DEFINED
enum eTradeEndReason { eTradeEndReason_0 = 0 };
#endif
#ifndef DNF_ENUM_EEXPADDREASON_DEFINED
#define DNF_ENUM_EEXPADDREASON_DEFINED
enum eExpAddReason { eExpAddReason_0 = 0 };
#endif
#ifndef DNF_ENUM_NOTIPACKET_DEFINED
#define DNF_ENUM_NOTIPACKET_DEFINED
enum ENUM_NOTIPACKET { ENUM_NOTIPACKET_0 = 0 };
#endif
#ifndef DNF_ENUM_QUEST_ENEMY_TYPE_DEFINED
#define DNF_ENUM_QUEST_ENEMY_TYPE_DEFINED
enum ENUM_QUEST_ENEMY_TYPE { ENUM_QUEST_ENEMY_TYPE_0 = 0 };
#endif
#ifndef DNF_ENUM_MONEY_FULL_REASON_DEFINED
#define DNF_ENUM_MONEY_FULL_REASON_DEFINED
enum ENUM_MONEY_FULL_REASON { ENUM_MONEY_FULL_REASON_0 = 0 };
#endif
enum ENUM_PACKETCLASS { ENUM_PACKETCLASS_0 = 0 };
#ifndef GAME_MISSIONTYPES_PVP_BATTLE_MODE_DEFINED
#define GAME_MISSIONTYPES_PVP_BATTLE_MODE_DEFINED
enum PVP_BATTLE_MODE
{
    PVP_BATTLE_MODE_0 = 0,
    PVP_BATTLE_MODE_1 = 1,
    PVP_BATTLE_MODE_2 = 2,
    PVP_BATTLE_MODE_3 = 3,
    PVP_BATTLE_MODE_4 = 4,
    PVP_BATTLE_MODE_5 = 5
};
#endif
#ifndef DNF_ENUM_DISCONN_SIG_DEFINED
#define DNF_ENUM_DISCONN_SIG_DEFINED
enum DISCONN_SIG
{
    DISCONN_SIG_0 = 0,
    DISCONN_SIG_5 = 5,
    DISCONN_SIG_0x30 = 0x30,
    DISCONN_SIG_0x31 = 0x31,
    DISCONN_SIG_0x32 = 0x32
};
#endif


#ifndef DNF_ENUM_SKILL_TREE_KIND_DEFINED
#define DNF_ENUM_SKILL_TREE_KIND_DEFINED
enum ENUM_SKILL_TREE_KIND
{
    SKILL_TREE_NONE = -1,
    SKILL_TREE_1 = 0,
    SKILL_TREE_2 = 1,
    SKILL_TREE_SFP_1 = 2,
    SKILL_TREE_SFP_2 = 3
};
#endif

#ifndef DNF_ENUM_ERIDABLEOBJECTSTATE_DEFINED
#define DNF_ENUM_ERIDABLEOBJECTSTATE_DEFINED
enum eRidableObjectState { eRidableObjectState_0 = 0 };
#endif
#ifndef DNF_ENUM_WARROOM_STATE_DEFINED
#define DNF_ENUM_WARROOM_STATE_DEFINED
enum WARROOM_STATE
{
    WARROOM_STATE_NEG1 = -1,
    WARROOM_STATE_0 = 0,
    WARROOM_STATE_1 = 1,
    WARROOM_STATE_2 = 2,
    WARROOM_STATE_3 = 3,
    WARROOM_STATE_4 = 4,
    WARROOM_STATE_5 = 5
};
#endif
#ifndef DNF_ENUM_PVP_MATCHING_TYPE_DEFINED
#define DNF_ENUM_PVP_MATCHING_TYPE_DEFINED
enum ENUM_PVP_MATCHING_TYPE { ENUM_PVP_MATCHING_TYPE_0 = 0 };
#endif
#ifndef DNF_ENUM_DUNGEON_CLEAR_CONDITION_TYPE_DEFINED
#define DNF_ENUM_DUNGEON_CLEAR_CONDITION_TYPE_DEFINED
enum ENUM_DUNGEON_CLEAR_CONDITION_TYPE { ENUM_DUNGEON_CLEAR_CONDITION_TYPE_0 = 0 };
#endif
enum ENUM_TITLE_BOOK_INFO_TYPE { ENUM_TITLE_BOOK_INFO_TYPE_0 = 0 };
#ifndef DNF_ENUM_PARTY_INFO_TYPE_DEFINED
#define DNF_ENUM_PARTY_INFO_TYPE_DEFINED
enum ENUM_PARTY_INFO_TYPE { ENUM_PARTY_INFO_TYPE_0 = 0 };
#endif

#endif  // DNF_GAME_GAMEENUMS_H_
